# Generated by Django 4.2.1 on 2023-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
