# Generated by Django 4.2.1 on 2023-06-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='phone',
            new_name='email',
        ),
    ]
