# Generated by Django 4.2.1 on 2023-06-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0005_rename_phone_otp_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='create',
            new_name='created',
        ),
    ]
